version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server 
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - default

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - 6000:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres:

networks:
   default: